# Generated by Django 3.2.7 on 2021-09-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='leaf2',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
